http.host: "0.0.0.0"
xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch:9200" ]

                                        // ============= logstash/pipeline/logstash.conf =============
                                        input {
                                        beats {
                                        port => 5044
                                        }
                                        
                                        tcp {
                                        port => 5044
                                        codec => json_lines
                                        }
}

  filter {
  if [fields][service] {
  mutate {
  add_field => { "service_name" => "%{[fields][service]}" }
  }
  }
  
  # Parse log level
  if [level] {
  mutate {
  add_field => { "log_level" => "%{level}" }
  }
  }
  
  # Add timestamp
  date {
  match => [ "@timestamp", "ISO8601" ]
  }
  
  # Parse stack traces
  if [message] =~ /Exception|Error/ {
  mutate {
  add_tag => [ "error" ]
  }
  }
}

  output {
  elasticsearch {
  hosts => ["http://elasticsearch:9200"]
  index => "logstash-spring-logs-%{+YYYY.MM.dd}"
  }
  
  stdout {
  codec => rubydebug
  }
}